import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, Timer
from cocotbext.axi import AxiBus, AxiRam

@cocotb.test()
async def test_boot_execution(dut):
    """Test RISC-V Core Booting C Code via AXI Ram."""
    
    # Start clock
    cocotb.start_soon(Clock(dut.clk, 10, units="ns").start())
    
    # Initialize AXI RAMs (Instruction and Data)
    # The RV64 core has instruction AXI (i_axi_*) and data AXI (d_axi_*)
    
    # Create buses. We assume generic AXI4 ports on rv_core_top.
    i_bus = AxiBus.from_prefix(dut, "imem")
    d_bus = AxiBus.from_prefix(dut, "dmem")
    
    # Initialize RAM at RESET_PC (0x20000)
    i_ram = AxiRam(i_bus, dut.clk, dut.rst_n, size=32768)
    d_ram = AxiRam(d_bus, dut.clk, dut.rst_n, size=32768)
    
    # Load the compiled C program into the instruction RAM!
    # Hex file generated by hexdump is word-based. We will read it.
    with open("boot.mem", "r") as f:
        lines = f.readlines()
        
    # Write into RAM
    address = 0x20000
    for line in lines:
        word = int(line.strip(), 16)
        i_ram.write(address, word.to_bytes(4, byteorder='little'))
        d_ram.write(address, word.to_bytes(4, byteorder='little')) # Data ram also gets it for literal loads
        address += 4

    # Reset
    dut.rst_n.value = 0
    await Timer(50, units="ns")
    dut.rst_n.value = 1
    
    cocotb.log.info("Reset released. CPU should begin fetching from 0x20000.")
    
    # Wait and monitor UART writes on data bus
    # Actually, we don't have a UART hooked up. But we can monitor AXI writes!
    
    # We wait for the CPU to write to the test memory address (0x20000000) or UART (0x10000000)
    # The cocotbext.axi Ram will log writes, but we can also just run for 1000 cycles.
    for i in range(1000):
        await RisingEdge(dut.clk)
        
        # Check if the core attempts an AXI write to UART or TEST PTR
        if dut.dmem_awvalid.value == 1 and dut.dmem_awready.value == 1:
            awaddr = int(dut.dmem_awaddr.value)
            if awaddr == 0x10000000:
                char = chr(int(dut.dmem_wdata.value) & 0xFF)
                cocotb.log.info(f"UART OUTPUT: {char}")
            elif awaddr == 0x20000000:
                val = int(dut.dmem_wdata.value)
                cocotb.log.info(f"TEST MEMORY WRITE: 0x{val:08X}")
                if val == 0xDEADBEEF:
                    cocotb.log.info("SUCCESS: CPU booted C payload and executed successfully!")
                    return
                
    cocotb.log.error("Simulation finished without seeing the expected memory writes.")
    assert False, "Boot failed or timed out."
